export const BEGIN_AJAX_CALL='BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR='AJAX_CALL_ERROR';

export const LOAD_OUTAGES_SUCCESS='LOAD_OUTAGES_SUCCESS';
export const CREATE_OUTAGE_SUCCESS='CREATE_OUTAGE_SUCCESS';
export const UPDATE_OUTAGE_SUCCESS='UPDATE_OUTAGE_SUCCESS';